GlobalShippingSolutions/Controllers/ContactUsController.cs
using GlobalShippingSolutions.Infrastructure;
using GlobalShippingSolutions.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GlobalShippingSolutions.Controllers
{
    public class ContactUsController : Controller
    {
        //ContactUs
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FeedbackModel model)
        {
            GenericResultModel result = new GenericResultModel();
           
            if (ModelState.IsValid)
            {
                EmailModel contactUsEmail = new EmailModel();
                contactUsEmail.To = System.Configuration.ConfigurationManager.AppSettings["AdminEmail"];
                contactUsEmail.Subject = "Global Shipping Solution - Contact Us";
                contactUsEmail.Body = "<html><body>Name : " + model.Name +
                    "<br />Email : " + model.Email +
                    "<br />Phone :" + model.Phone +
                    "<br />Comments :" + model.Comments +                    
                    "</body></html>";

                AsyncSendingEmail ASendAdminEmail = new AsyncSendingEmail(contactUsEmail, true);
                ASendAdminEmail.SendAsynchronously();

                EmailModel userEmail = new EmailModel();
                userEmail.To = model.Email;
                userEmail.Subject = "Global Shipping Solution - Acknowledgment";
                userEmail.Body = "<html><body>Dear " + model.Name +
                    "<br /><br />Thank you so much for contacting Global Shipping Solutions, relevant person will be in touch with you soon" +
                    "<br /><br />Regards" +
                    //"<br /><br /><a href=\"http://www.fastecsol.com\"><img src=\"http://www.fastecsol.com/Content/images/logo.png\" alt=\"Logo\"></a>" +
                    "</body></html>";

                AsyncSendingEmail ASendUserEmail = new AsyncSendingEmail(userEmail, true);
                ASendUserEmail.SendAsynchronously();
                    
                result.Success = true;
            }
            else
            {
                result.Success = false;
                result.ErrorCode = 10;
                result.ModelErrorDetails = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToList();
            }            

            return Json(result);
        }

    }
}

GlobalShippingSolutions/Views/ContactUs/Index.cshtml
@model GlobalShippingSolutions.Models.FeedbackModel
@{
    ViewBag.Title = "Contact Us";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section OptionalCSS{
    <style type="text/css">
        .btn{
            padding: 6px 50px;
            margin-left:20px;
        }
    </style>
}

@section OptionalJavaScriptTop{
    <script src="/Scripts/jquery.validate.min.js"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

<div class="container">
    <h2>Contact Us</h2> 
    <div class="col-md-10 noPadding" style="margin-top:0px;">
        <h3>Global Shipping Solution Inc</h3>
        <p>We are located in Ontario</p>
    </div> 
    <div class="col-md-12 noPadding" style="margin-bottom: 20px;">
        <div class="col-md-9 noPadding">
            <iframe scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.ca/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=1744+Meyerside+Dr,+Suite+103,+Mississauga,+ON,+L5T+1A3,+Canada.&amp;sll=49.891235,-97.15369&amp;sspn=29.938904,57.919922&amp;ie=UTF8&amp;hq=&amp;hnear=1744+Meyerside+Dr,+Mississauga,+Peel+Regional+Municipality,+Ontario&amp;ll=43.674825,-79.643841&amp;spn=0.00818,0.014141&amp;z=14&amp;iwloc=A&amp;output=embed" style="width: 850px; height: 450px" frameborder="0" height="220" width="410"></iframe><br><small><a href="http://maps.google.ca/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=1744+Meyerside+Dr,+Suite+103,+Mississauga,+ON,+L5T+1A3,+Canada.&amp;sll=49.891235,-97.15369&amp;sspn=29.938904,57.919922&amp;ie=UTF8&amp;hq=&amp;hnear=1744+Meyerside+Dr,+Mississauga,+Peel+Regional+Municipality,+Ontario&amp;ll=43.674825,-79.643841&amp;spn=0.00818,0.014141&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>        
        </div>
        <div class="col-md-3">
            <div class="col-md-12">
                <div class="col-md-1 noPadding">
                    <img border="0" width="25" height="25" src="/Content/Images/Small_Icon_address.gif">
                </div>
                <div class="col-md-11" style="padding-left:25px;">
                    <b><u>Corporate Office</u>: </b><br />
                        1744 Meyerside Dr, Suite 103
                        Mississauga, ON, L5T 1A3
                        Canada.
                </div>
            </div>
            <div class="col-md-12" style="margin-top:15px;">
                <div class="col-md-1 noPadding">
                    <img border="0" width="25" height="25" src="/Content/Images/Small_Icon_phone.gif">
                </div>
                <div class="col-md-11" style="padding-left:25px;">
                    <b>Telephone:</b> <br>
                    905-670-2019
                </div>
            </div>
            <div class="col-md-12" style="margin-top:15px;">
                <div class="col-md-1 noPadding">
                    <img border="0" width="25" height="25" src="/Content/Images/Small_Icon_fax.gif">
                </div>
                <div class="col-md-11" style="padding-left:25px;">
                    <b>
                        Fax:<br>
                    </b> 905-670-5762
                </div>
            </div>
            <div class="col-md-12" style="margin-top:15px;">
                <div class="col-md-1 noPadding">
                    <img border="0" width="25" height="25" src="/Content/Images/Small_Icon_email.gif">
                </div>
                <div class="col-md-11" style="padding-left:25px;">
                    <b>E-mail Address:</b><br>
                    <a href="mailto:info@globalshippingsolution.ca">
                        info@globalshippingsolution.ca
                    </a>
                </div>
            </div>
            <div class="col-md-12" style="margin-top:15px;">
                <div class="col-md-1 noPadding">
                    <img border="0" width="25" height="25" src="/Content/Images/Small_Icon_address.gif">
                </div>
                <div class="col-md-11" style="padding-left:25px;">
                    <u><b>USA Office:</b></u><span style="font-size: 10pt; color: #10447a; text-decoration: underline">
                        <br>
                    </span>810 Harbor Town Blvd,<br>
                    Perth Amboy, NJ. 08861, USA
                </div>
            </div>
            <div class="col-md-12" style="margin-top:15px;">
                <div class="col-md-1 noPadding">
                    <img border="0" width="25" height="25" src="/Content/Images/Small_Icon_phone.gif">
                </div>
                <div class="col-md-11" style="padding-left:25px;">
                    <b>E-mail Address:</b><br>
                    <a href="mailto:info@globalshippingsolution.ca">
                        info@globalshippingsolution.ca
                    </a>
                </div>
            </div>               
        </div>
    </div>

    @using (Html.BeginForm("Index", "ContactUs", FormMethod.Post, new { @id = "airCargoQuote" }))
    {
        <div class="row" style="margin-bottom:20px;">
            <div class="col-md-12 noPadding">
                <div class="control-group form-group">
                    <div class="controls">
                        <div class="col-md-2">
                            @Html.LabelFor(model => model.Name)
                        </div>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        </div>
                        <div class="col-md-3">
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 noPadding">
                <div class="control-group form-group">
                    <div class="controls">
                        <div class="col-md-2">
                            @Html.LabelFor(model => model.Email)
                        </div>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        </div>
                        <div class="col-md-3">
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 noPadding">
                <div class="control-group form-group">
                    <div class="controls">
                        <div class="col-md-2">
                            @Html.LabelFor(model => model.Phone)
                        </div>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                        </div>
                        <div class="col-md-3">
                            @Html.ValidationMessageFor(model => model.Phone)
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 noPadding">
                <div class="control-group form-group">
                    <div class="controls">
                        <div class="col-md-2">
                            @Html.LabelFor(model => model.Comments)
                        </div>
                        <div class="col-md-7">
                            @Html.TextAreaFor(model => model.Comments, new { @class = "main_textarea", @cols = "4", @rows = "4" })
                        </div>
                        <div class="col-md-3">
                            @Html.ValidationMessageFor(model => model.Comments)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- /.row -->

        @Html.ValidationSummary(true)
        
        <div class="col-md-12 noPadding">
            <div class="col-md-2">
                &nbsp;
            </div>
            <div class="col-md-7 noPadding">
                <input type="submit" class="btn btn-primary" value="Submit Feedback/Question" id="submit" style="margin-left:0px;" />
                <input type="button" class="btn btn-primary" value="Clear" id="cancel" onclick="window.location = '/ContactUs';" />
            </div>            
        </div>
    }

        <div class="col-md-12 noPaddingBoth">
            <hr />
        </div>
        <div class="col-md-12 noPadding" style="margin-top:20px;">
            <div class="col-md-4">
                <img src="~/Content/Images/p11.jpg" style="min-width:100%;" />
            </div>
            <div class="col-md-4">
                <img src="~/Content/Images/p22.jpg" style="min-width:100%;" />
            </div>
            <div class="col-md-4">
                <img src="~/Content/Images/p33.jpg" style="min-width:100%;" />
            </div>
        </div>
    </div>

@section OptionalJavaScriptBottom{
    <script type="text/javascript">
        $("form").submit(function () {
            if (!$(this).valid()) {
                return false;
            }
            else {
                $('input[type="submit"]').prop('disabled', true);
                $.ajax({
                    beforeSend: function () { $("#ajax-loader").css('visibility', 'visible'); },
                    data: $("form").serialize(),
                    type: $("form").attr('method'),
                    url: $("form").attr('action'),
                    success: function (data) {
                        $("#ajax-loader").css('visibility', 'hidden');
                        if (data.Success) {                            
                            Cookies.set('EnableNotify', 'Your message has been successfully sent. Please allow up to 48 hours for a reply! Thank you!');
                            window.location = "/ContactUs";
                        } else {
                            if (data.ErrorCode == 11) {
                                showNotification(data.ErrorMessage, "error");
                            } else {
                                var errorList = data.ModelErrorDetails;
                                for (var i = 0; i < errorList.length; i++) {
                                    var name = errorList[i].Key;
                                    var message = errorList[i].Errors[0].ErrorMessage;
                                    var error = {};
                                    error[name] = message;
                                    $("#quoteRequestForm").validate().showErrors(error);
                                    $('#' + name).parent().children("span").text(message).css("display", "inline");
                                }
                            }
                        }
                    }
                });
                return false;
            }
        });
    </script>
}